[package]
name = "pardalotus_snapshot_tool"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.94"
clap = "4.5.23"
flate2 = "1.0.35"
serde_json = "1.0.133"
structopt = "0.3.26"
tar = "0.4.43"
